import type { NextPage } from "next";
import Head from "next/head";
import argon2 from "argon2";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  let loginMutation = trpc.useMutation("auth-v1.login", {
    onSuccess: (user) => {
      console.log(user);
    },
  });
  let registerMutation = trpc.useMutation("auth-v1.register");

  const login = () => {
    loginMutation.mutate({
      email: "masmeert@gmail.com",
      password: "superpassword",
    });
  };
  const register = () => {
    registerMutation.mutate({
      email: "masmeert@gmail.com",
      password: "superpassword",
      surname: "Meert",
      forename: "Massimo",
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={login}>login</button>
      {loginMutation.error && (
        <p>Something went wrong! {loginMutation.error.message}</p>
      )}
      <button onClick={register}>register</button>
      {registerMutation.error && (
        <p>Something went wrong! {registerMutation.error.message}</p>
      )}
    </>
  );
};

export default Home;
