import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>pgvins</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/auth/login">login | </Link>
      <Link href="/auth/register">register | </Link>
      <Link href="/wines">wines</Link>
    </>
  );
};

export default Home;
